language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode

gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile

notifications:
  irc: "irc.freenode.org#projecthydra"

before_install:
  - gem install bundler
